/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controler.PedidoControler;
import DAO.Conexao;
import DAO.UsuarioDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import Controler.UsuarioControler;
import static Controler.UsuarioControler.pree;

/**
 *
 * @author victor
 */
public class menuView extends javax.swing.JFrame {

    private final UsuarioControler UControler;
    private final PedidoControler PControler;
    /**
     * Creates new form menuView
     */
    public menuView() {
        initComponents();
        UControler  = new UsuarioControler(this);
        PControler = new PedidoControler(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1DELETE = new javax.swing.JButton();
        jButtonMostraBanco = new javax.swing.JButton();
        jButtonMostraID = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jTextFieldIDDELETE = new javax.swing.JTextField();
        jTextFieldIDSELECT = new javax.swing.JTextField();
        jTextFieldIDUPDATE = new javax.swing.JTextField();
        jTextFieldUPUSU = new javax.swing.JTextField();
        jTextFieldUPSENHA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_Pedido = new javax.swing.JTable();
        jTextFieldDESCRICAO = new javax.swing.JTextField();
        jTextFieldVALORP = new javax.swing.JTextField();
        jTextFieldIDUSUARIOPEDIDO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonADDPEDIDO = new javax.swing.JButton();
        jButtonSELECTALLP = new javax.swing.JButton();
        jButtonMOSTRAPUSU = new javax.swing.JButton();
        jTextFieldPESQUISAPEDIDOID = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1DELETE.setText("delete");
        jButton1DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DELETEActionPerformed(evt);
            }
        });

        jButtonMostraBanco.setText("select all");
        jButtonMostraBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostraBancoActionPerformed(evt);
            }
        });

        jButtonMostraID.setText("select 1");
        jButtonMostraID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostraIDActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "USUARIO", "SENHA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jTextFieldIDDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDDELETEActionPerformed(evt);
            }
        });

        jTextFieldIDSELECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDSELECTActionPerformed(evt);
            }
        });

        jTextFieldIDUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDUPDATEActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("USUARIO");

        jLabel3.setText("SENHA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonMostraBanco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMostraID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldIDUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUPUSU, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldUPSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1DELETE)
                    .addComponent(jTextFieldIDDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMostraBanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostraID)
                    .addComponent(jTextFieldIDSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jTextFieldIDUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUPUSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUPSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BD", jPanel1);

        Tabela_Pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descricao", "Valor", "ID Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabela_Pedido);

        jTextFieldDESCRICAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDESCRICAOActionPerformed(evt);
            }
        });

        jTextFieldIDUSUARIOPEDIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDUSUARIOPEDIDOActionPerformed(evt);
            }
        });

        jLabel4.setText("Descrição");

        jLabel5.setText("Valor");

        jLabel6.setText("ID Usuario");

        jButtonADDPEDIDO.setText("Adicionar pedido");
        jButtonADDPEDIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDPEDIDOActionPerformed(evt);
            }
        });

        jButtonSELECTALLP.setText("Mostrar tudo");
        jButtonSELECTALLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSELECTALLPActionPerformed(evt);
            }
        });

        jButtonMOSTRAPUSU.setText("Mostrar por USUARIO");
        jButtonMOSTRAPUSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMOSTRAPUSUActionPerformed(evt);
            }
        });

        jTextFieldPESQUISAPEDIDOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPESQUISAPEDIDOIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldVALORP)
                                    .addComponent(jTextFieldIDUSUARIOPEDIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonADDPEDIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButtonSELECTALLP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMOSTRAPUSU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPESQUISAPEDIDOID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldVALORP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldIDUSUARIOPEDIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonADDPEDIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSELECTALLP)
                    .addComponent(jButtonMOSTRAPUSU)
                    .addComponent(jTextFieldPESQUISAPEDIDOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedido", jPanel3);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("testa usuario DAO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        try {
            Connection conexao = new Conexao().getConnection();
            
            UsuarioDAO usuarioDao = new UsuarioDAO(conexao);
            
            //tets

            
            Usuario usuarioInsert = new Usuario("TesteDAO","1357");
            Usuario usuarioInserido = usuarioDao.insert(usuarioInsert);
            System.out.println(usuarioInserido.getUsuario()+" "+usuarioInserido.getSenha()+" "+usuarioInserido.getId());
            //tets
            //Usuario usuarioselecionado = usuarioDao.selectID(usuarioInserido);
            //tets
            //usuarioDao.delete(usuarioselecionado);
            //tets
            ArrayList<Usuario> usuarios = usuarioDao.selectAll();
            
            for(Usuario usuario : usuarios){
                System.out.println(usuario.getUsuario());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextFieldIDUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDUPDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDUPDATEActionPerformed

    private void jTextFieldIDSELECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDSELECTActionPerformed

    }//GEN-LAST:event_jTextFieldIDSELECTActionPerformed

    private void jTextFieldIDDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDDELETEActionPerformed

    }//GEN-LAST:event_jTextFieldIDDELETEActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            UControler.atualiza();
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonMostraIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostraIDActionPerformed
        try {
            UControler.selectid();
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMostraIDActionPerformed

    private void jButtonMostraBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostraBancoActionPerformed

        try {
            UControler.selectall();
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonMostraBancoActionPerformed

    private void jButton1DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DELETEActionPerformed

        try {
            UControler.Deletar();
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1DELETEActionPerformed

    private void jButtonADDPEDIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDPEDIDOActionPerformed
       try {
            PControler.insere();
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonADDPEDIDOActionPerformed

    private void jButtonSELECTALLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSELECTALLPActionPerformed
        try {
            PControler.selectall();
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSELECTALLPActionPerformed

    private void jButtonMOSTRAPUSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMOSTRAPUSUActionPerformed
        try {
            PControler.selectid();
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMOSTRAPUSUActionPerformed

    private void jTextFieldDESCRICAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDESCRICAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDESCRICAOActionPerformed

    private void jTextFieldIDUSUARIOPEDIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDUSUARIOPEDIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDUSUARIOPEDIDOActionPerformed

    private void jTextFieldPESQUISAPEDIDOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPESQUISAPEDIDOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPESQUISAPEDIDOIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               menuView mv = new menuView();
               mv.setVisible(true);
               
                try {
                    preencheTabela();
                } catch (SQLException ex) {
                    Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public static void preencheTabela() throws SQLException{
        try {
            UsuarioControler.pree();
            
        } catch (SQLException ex) {
            Logger.getLogger(menuView.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }

    public JTextField getjTextFieldIDDELETE() {
        return jTextFieldIDDELETE;
    }

    public void setjTextFieldIDDELETE(JTextField jTextFieldIDDELETE) {
        this.jTextFieldIDDELETE = jTextFieldIDDELETE;
    }

    public JTextField getjTextFieldIDSELECT() {
        return jTextFieldIDSELECT;
    }

    public void setjTextFieldIDSELECT(JTextField jTextFieldIDSELECT) {
        this.jTextFieldIDSELECT = jTextFieldIDSELECT;
    }

    public JTextField getjTextFieldIDUPDATE() {
        return jTextFieldIDUPDATE;
    }

    public void setjTextFieldIDUPDATE(JTextField jTextFieldIDUPDATE) {
        this.jTextFieldIDUPDATE = jTextFieldIDUPDATE;
    }

    public JTextField getjTextFieldUPSENHA() {
        return jTextFieldUPSENHA;
    }

    public void setjTextFieldUPSENHA(JTextField jTextFieldUPSENHA) {
        this.jTextFieldUPSENHA = jTextFieldUPSENHA;
    }

    public JTextField getjTextFieldUPUSU() {
        return jTextFieldUPUSU;
    }

    public void setjTextFieldUPUSU(JTextField jTextFieldUPUSU) {
        this.jTextFieldUPUSU = jTextFieldUPUSU;
    }

    public JTextField getjTextFieldDESCRICAO() {
        return jTextFieldDESCRICAO;
    }

    public void setjTextFieldDESCRICAO(JTextField jTextFieldDESCRICAO) {
        this.jTextFieldDESCRICAO = jTextFieldDESCRICAO;
    }

    public JTextField getjTextFieldIDUSUARIOPEDIDO() {
        return jTextFieldIDUSUARIOPEDIDO;
    }

    public void setjTextFieldIDUSUARIOPEDIDO(JTextField jTextFieldIDUSUARIOPEDIDO) {
        this.jTextFieldIDUSUARIOPEDIDO = jTextFieldIDUSUARIOPEDIDO;
    }

    public JTextField getjTextFieldVALORP() {
        return jTextFieldVALORP;
    }

    public void setjTextFieldVALORP(JTextField jTextFieldVALORP) {
        this.jTextFieldVALORP = jTextFieldVALORP;
    }

    public JTextField getjTextFieldPESQUISAPEDIDOID() {
        return jTextFieldPESQUISAPEDIDOID;
    }

    public void setjTextFieldPESQUISAPEDIDOID(JTextField jTextFieldPESQUISAPEDIDOID) {
        this.jTextFieldPESQUISAPEDIDOID = jTextFieldPESQUISAPEDIDOID;
    }
    
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabela;
    public static javax.swing.JTable Tabela_Pedido;
    private javax.swing.JButton jButton1DELETE;
    private javax.swing.JButton jButtonADDPEDIDO;
    private javax.swing.JButton jButtonMOSTRAPUSU;
    private javax.swing.JButton jButtonMostraBanco;
    private javax.swing.JButton jButtonMostraID;
    private javax.swing.JButton jButtonSELECTALLP;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldDESCRICAO;
    private javax.swing.JTextField jTextFieldIDDELETE;
    private javax.swing.JTextField jTextFieldIDSELECT;
    private javax.swing.JTextField jTextFieldIDUPDATE;
    private javax.swing.JTextField jTextFieldIDUSUARIOPEDIDO;
    private javax.swing.JTextField jTextFieldPESQUISAPEDIDOID;
    private javax.swing.JTextField jTextFieldUPSENHA;
    private javax.swing.JTextField jTextFieldUPUSU;
    private javax.swing.JTextField jTextFieldVALORP;
    // End of variables declaration//GEN-END:variables

}
